# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Extra Fun Project
email: fadhriz.stelar@gmail.com
description:  # this means to ignore newlines until "baseurl:"
  DISCLAIMER;

  This is only for project, without any warranty. It is not the best advice,
  so please use it at your own risk.
  Make sure you do the backup every time you do this.
  Everything here is through the help of Google.com,
  you can help yourself in there.

  Regards,

  Farz-hkh
#baseurl: "" # the subpath of your site, e.g. /blog
url: "https://farz-hkh.github.io/extra182" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: FadhrizStelar
github_username:  farz-hkh

# Build settings
markdown: kramdown
author: Farz-hkh
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/


# github: [metadata]
encoding: UTF-8
timezone: Asia/Jakarta
show_downloads: true
share: true
collections:
  authors:
    output: true

defaults:
  - scope:
      path: ""
      type: "authors"
    values:
      layout: "author"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"

# Google Analytics
google_analytics: UA-89852122-1

#plugins:
#  - jekyll-gist
#  - jemoji

# CAN CHANGE
# encoding: UTF-8
# kramdown:
#   input: GFM
#   hard_wrap: false
# future: true
# jailed: false
# gfm_quirks: paragraph_end
# CAN NOT CHANGE
# lsi: false
# safe: true
# source: [your repo's top level directory]
# incremental: false
# highlighter: rouge
# gist:
#   noscript: false
# kramdown:
#   math_engine: mathjax
#   syntax_highlighter: rouge
